services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hassam
      MONGO_INITDB_ROOT_PASSWORD: hassam
      MONGO_INITDB_DATABASE: careerhub
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  backend:
    image: hassamahmad/careerhub-backend:BACKEND_IMAGENAME
    container_name: careerhub-backend
    restart: always
    env_file: ../backend/.env
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - mern-app
    ports:
      - "6006:6006"
    depends_on:
      - mongo

  careerhub:
    image: hassamahmad/careerhub-frontend:FRONTEND_IMAGENAME
    container_name: careerhub-frontend
    restart: always
    volumes:
      - ../careerhub:/app
      - /app/node_modules
    networks:
      - mern-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:6006 # If using Vite

volumes:
  mongo_data:

networks:
  mern-app:
    driver: bridge
